// ALL SKIP STATEMENTS THAT AFFECT THIS SHADER!!!
// defined $LIGHTING_PREVIEW && defined $FASTPATH && $LIGHTING_PREVIEW && $FASTPATH

#pragma once
#include "shaderlib/cshader.h"
class gauss_blur_3x3_vs30_Static_Index
{
public:
	gauss_blur_3x3_vs30_Static_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderStaticTest_gauss_blur_3x3_vs30 1


class gauss_blur_3x3_vs30_Dynamic_Index
{
public:
	gauss_blur_3x3_vs30_Dynamic_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderDynamicTest_gauss_blur_3x3_vs30 1

